### ISSUE TITLE
Error: EPERM: operation not permitted, uv_cwd

### ISSUE THREAD

**Issue by gitjps** [carbon-design-system/gatsby-theme-carbon#778]
## Detailed description

I followed the instructions on Macos  10.15.3 https://gatsby-theme-carbon.now.sh/getting-started/

> What did you expect to happen? What happened instead? What would you like to see changed?

complete installation

> What browser are you working in?
 
none so far

## Steps to reproduce the issue

```
% npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme
/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:39
  return localBinPath(process.cwd()).then(local => {
                              ^

Error: EPERM: operation not permitted, uv_cwd
    at npx (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:39:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npx-cli.js:8:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

## Additional information

- Screenshots or code
- Notes

**Comment by gitjps** [comment]
I was accidentally in the .Trash folder and terminal apparently did not have permissions.
