### ISSUE TITLE
gatsby develop failed: Unexpected character `/` (U+002F)

### ISSUE THREAD

**Issue by shikunli-qq** [carbon-design-system/gatsby-theme-carbon#987]
## Detailed description

Cannot run `gatsby develop` successfully 

## Steps to reproduce the issue

1. Installed Node.js 
2. Run ` npm install --global windows-build-tools --vs2015`
3. Installed Git
4. Installed Gatsby CLI
5. Run `npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme`

All the above steps run successfully

## Additional information

- log:

```
 ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreatePage lifecycle:

Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_`

  83 |             files = _context.sent;
  84 |             files.forEach(function (file) {
> 85 |               (0, _createPageWrapper.createPage)(file, pagesDirectory, actions, ignore, graphql, reporter);
     |                                                 ^
  86 |             });
  87 |             (0, _gatsbyPageUtils.watchDirectory)(pagesPath, pagesGlob, function (addedPath) {
  88 |               try {

File: node_modules\gatsby-plugin-page-creator\gatsby-node.js:85:49



  Error: C:/Gatsby/my-carbon-site/src/pages/components/markdown.mdx:131:33: Unex  pected character `/` (U+002F) before local name, expected a character that can   start a name, such as a letter, `$`, or `_`
      (No stack trace)

```

- Environment
I am using a VM with Windows installed
![image](https://user-images.githubusercontent.com/51906704/92582856-13ec8180-f2c4-11ea-81fb-af5cf82938a4.png)

**Comment by kkckkc** [comment]
I have the same issue when running from the main branch, i.e. something like

```
git clone https://github.com/carbon-design-system/gatsby-theme-carbon.git
cd gatsby-theme-carbon/packages/example
npm install
npm run dev
```

My exact error is 

```
Error: /Users/magnusjohansson/Documents/Work/internal-projects/liberty/temp/gatsby-theme-carbon/packages/example/src/pages/components/markdown.mdx:144:33: Unexpected character `/`   (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_`
      (No stack trace)
```

This is on Mac with node version 13.13.0


It's also worth knowing that if I empty `markdown.mdx` to get around the issue, I get the following warnings in my browser

```
react_devtools_backend.js:2273 Component FeatureCard was not imported, exported, or provided by MDXProvider as global scope 
    at MDXDefaultShortcode
    at http://localhost:8000/commons.js:171468:30
    at div
    at Grid (http://localhost:8000/commons.js:260171:23)
    at Main (http://localhost:8000/commons.js:263781:203)
    at main
    at Container (http://localhost:8000/commons.js:256217:23)
    at Layout (http://localhost:8000/commons.js:262472:23)
    at Homepage (http://localhost:8000/commons.js:268946:23)
    at ShadowedHomepage
    at http://localhost:8000/commons.js:171468:30
    at MDXContent (http://localhost:8000/commons.js:361415:25)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at HotExportedMDXContent (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at PageRenderer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at PageQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at RouteHandler
    at div
    at FocusHandlerImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at FocusHandler (http://localhost:8000/commons.js:172889:19)
    at RouterImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:172629:23)
    at Router
    at ScrollHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at RouteUpdates (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at EnsureResources (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at LocationHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:172629:23)
    at Root
    at MDXProvider (http://localhost:8000/commons.js:171445:25)
    at MDXScopeProvider (http://localhost:8000/commons.js:252267:25)
    at http://localhost:8000/commons.js:252747:37
    at http://localhost:8000/commons.js:171429:48
    at MDXProvider (http://localhost:8000/commons.js:253685:46)
    at MDXProvider (http://localhost:8000/commons.js:263464:30)
    at ThemeProvider
    at ThemeProvider (http://localhost:8000/commons.js:266979:23)
    at NavContextProvider (http://localhost:8000/commons.js:269185:23)
    at StaticQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:322445:10), <anonymous>:14:7)
    at _default
overrideMethod @ react_devtools_backend.js:2273
MDXDefaultShortcode @ index.mdx:11
renderWithHooks @ react-dom.development.js:14804
mountIndeterminateComponent @ react-dom.development.js:17483
beginWork @ react-dom.development.js:18597
beginWork$1 @ react-dom.development.js:23180
performUnitOfWork @ react-dom.development.js:22155
workLoopSync @ react-dom.development.js:22131
performSyncWorkOnRoot @ react-dom.development.js:21757
scheduleUpdateOnFiber @ react-dom.development.js:21189
updateContainer @ react-dom.development.js:24374
(anonymous) @ react-dom.development.js:24759
unbatchedUpdates @ react-dom.development.js:21904
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24758
render @ react-dom.development.js:24841
(anonymous) @ app.js:103
setTimeout (async)
(anonymous) @ ready.js:37
(anonymous) @ app.js:102
Promise.then (async)
(anonymous) @ app.js:95
Promise.then (async)
(anonymous) @ app.js:24
./.cache/app.js @ app.js:17
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
0 @ index.scss?61ac:45
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
```


It's not only with a fresh clone and the example project I get these sort of errors. In fact, I started to get these errors when upgrading an old site we have. I see the following errors:

1. The Unexpected character error - I managed to work around this by changing content
2. The carbon components not loading (the second error message above) - I could sort of work around this by some hacks in `carbon-browser.js`
3. Images not loading (except for SVGs) - I have not been able to find any type of workaround for this issue

**Comment by jnm2377** [comment]
@kkckkc you don't have to `cd` into the `example` directory to run `yarn dev`. You should just do that at the root level of the repo.

**Comment by jnm2377** [comment]
@shikunli-qq You said the first few steps ran successfully, so is the error only being thrown when you try to start your local env?

**Comment by vpicone** [comment]
Gonna close this out for now, hope you were able to resolve your issue!

**Comment by aqp696** [comment]
I have the same problem described in the issue. I tried in Windows, macos and linux with the same error with the latest code. If I remove markdown.mdx I can visualize the site, but the components, code ... are not rendered

**Comment by aqp696** [comment]
Forget it. I see the workaround in this issue #978
